content/4-blog/kirby-meets-dropbox/moved.txt

I believe this line is used to create the link to the new page.

Fixes link to new Docs page

---

content/1-docs/5-panel/1-blueprints/3-form-fields/docs.txt
content/1-docs/8-solutions/03-blog/07-rss/docs.txt

There are two small typos in the blueprint -> form fields -> validator section I think. This pull request fixes it.

Some small typos in the panels docs.

---

content/1-docs/7-advanced/2-routing/docs.txt

Added the information from http://getkirby.com/forum/general/20141124/multi-language-routing/#20141216105011

Short example for multi-language router

---

content/1-docs/6-languages/5-supporting-RTL-languages/docs.txt

Thought it might be nice not only to have RTL support in the panel, but offer a documentation how users could implement languages with RTL reading directions in their own front setup.

Doc added for supporting RTL reading direction

---

content/1-docs/5-panel/1-blueprints/4-file-settings/docs.txt

A first documentation of the new blueprint file options (type, size, width, height).

First doc of blueprint file options

---

content/1-docs/9-cheatsheet/0-panel-fields/0-tags/cheatsheet.item.txt

https://github.com/getkirby/panel/issues/513

Corrects Tags field lowercase option

---

site/blueprints/docs.php

ps: i'm sorry for the latest wrong pull req.

add the missing description in docs blueprint

---

content/1-docs/11-cheatsheet/0-options/0-headers/cheatsheet.item.txt

I had a litte discussion in the forum about how to use the headers option.
<http://forum.getkirby.com/t/how-does-the-header-option-work/1843>
So I decided to update the docs with an better example.
(There will be another pull request following when I add wildcards to the headers option)

add an better explanation for the headers option

---

content/1-docs/6-languages/3-variables/docs.txt

Just a small typo. 
It's my first pull request, so I hope I've done everything right. If not, please let me know :)

Fixed typo in language documentation

---

content/1-docs/10-security/docs.txt

Changes:
* make clear that you do not need to buy a cert, you can also get it free
* added information about setting up the SSL config yourself
What could be added (discuss this if you want):

Security docs updated

---

content/1-docs/8-advanced/2-routing/docs.txt

The question about [combining custom data with routing in a multi-language site](http://forum.getkirby.com/t/how-is-it-possible-to-combine-routing-variables-and-multi-language-support/1938?u=lukasbestle) has come up multiple times in the forum now, so I think it makes sense to include an example in the docs.

Add information about routing with custom data

---

content/1-docs/11-cheatsheet/0-options/0-languages/cheatsheet.item.txt

Put in the same example as in the docs. 
Much easier to understand the syntax this way.

Extended example

---

content/1-docs/2-getting-started/docs.txt

Add note on avoiding capital letters in filenames

Update Getting Started Guide

---

content/1-docs/8-cookbook/0-deploying-with-capistrano/cookbook-section.txt

> In this guide, we'll walk through the process of setting up Capistrano to deploy a website built on Kirby. You'll learn a bit about server configuration and best practices, and how to improve your process for updating projects.
Hey! 👋 
I think this is in a place where I'd like to get the community's eyes on it.
I'll issue a new PR for any updates, but it feels solid enough to publish.
Thanks for the encouragement, everyone!

Add Capistrano Deployment “recipe” to Cookbook

---

content/1-docs/8-cookbook/0-custom-metatags/cookbook-section.txt

change 'site->description()->html()' on line 53 to '$site->description()->html()'

fix example code error in cookbook-section.txt

---

content/1-docs/2-getting-started/docs.txt

- to Cookbook - RSS-Feeds
- to Cookbook

fix 2 relative links

---

content/1-docs/7-developer-guide/3-panel/1-fields/docs.txt

.field-help is outside of .field-content

Fixed HTML anatomy of a field

---

content/1-docs/5-panel/1-blueprints/3-page-settings/docs.txt

`delete` is the correct (working) syntax. See [line #35 of this file](https://github.com/getkirby/getkirby.com/pull/341/files#diff-38d81f8a2e67bc34da843cc65a08f7beL35).

Fix code example

---

site/templates/cookbook.index.php

Link cookbook categories to make it easier to get recipes of the same category

Feature: Cookbook categories

---

content/1-docs/8-cookbook/0-blog/cookbook-section.txt

Corrected some typos, fixed some spacing inconsistencies, smartened up some punctuation.

Minor edits to “Creating a Kirby-powered blog”

---

content/privacy/privacy.txt

Fix typo in privacy.txt

---

content/1-docs/7-developer-guide/4-advanced/7-emails/docs.txt

See https://github.com/getkirby/kirby/issues/646.

Fix code examples in email developer guide
